;;; micro-light-theme.el --- Emacs 24 theme with a light background.
;;; 查看当前光标下的字符信息
;;;method-1: M-x describe-face 命令，查看当前字符face信息
;;;method-2: M-x what-cursor-position命令，查看当前字符face信息(可能不显示face信息)
;;;method-3: [C-u C-x =]快捷键，查看当前字符face信息(是method-2的快捷键)

;;;theme: 查看各个 xxx_mode的关键字信息，然后设置对应的font_lock face

;;; others: change from light-soap-theme, thanks original author

;; Commentary:
;;Micro V0.01: 1. hight contrast theme, 2.for verilog type word 3. org date

;;; Code:


(deftheme micro-light)
(let ((class '((class color) (min-colors 89)))
     ;(fg1 "#474747")
      (fg1 "#000000")
      (fg2 "#545454")
      (fg3 "#616161")
      (fg4 "#6f6f6f")
      ;(bg1 "#fafadf")
      (bg1 "#fdf4c1")
      (bg2 "#e4e3c1")
     ;(bg3 "#cdcdaf")
      (bg3 "#555555")
      (bg4 "#b8b89c")
      (key2 "#615d86")
      (key3 "#47436a")
     ;(builtin "#365f71")
      (builtin "#000000")
      (keyword "#4f4b78")
      (const   "#794732")
     ;(comment "#ac44ff")
      (comment "#B0B0B0")
      (func    "#86546d")
      (str     "#555d3e")
     ;(type    "#5a532d")
      (type    "#4f4b78")
      (var     "#5f3041")
      (warning "#f70f2a"))
  (custom-theme-set-faces
   'micro-light
   `(default ((,class (:background ,bg1 :foreground ,fg1))))
   `(font-lock-builtin-face ((,class (:foreground ,builtin))))
   `(font-lock-comment-face ((,class (:foreground ,comment))))
   `(font-lock-negation-char-face ((,class (:foreground ,const))))
   `(font-lock-reference-face ((,class (:foreground ,const))))
   `(font-lock-constant-face ((,class (:foreground ,const))))
   `(font-lock-doc-face ((,class (:foreground ,comment))))
  ;`(font-lock-function-name-face ((,class (:foreground ,func :bold t :height 1.2))))
  ;`(font-lock-keyword-face ((,class (:bold ,class :foreground ,keyword :height 1.2))))
   `(font-lock-function-name-face ((,class (:foreground ,func :bold t ))))
   `(font-lock-keyword-face ((,class (:bold ,class :foreground ,keyword ))))
   `(font-lock-string-face ((,class (:foreground ,str))))
   ;`(font-lock-type-face ((,class (:foreground ,type ))))
   `(font-lock-type-face ((,class (:bold t :foreground ,type ))))
   `(font-lock-variable-name-face ((,class (:foreground ,var))))
   `(font-lock-warning-face ((,class (:foreground ,warning :background ,bg2))))
   `(region ((,class (:background ,fg3 :foreground ,bg2))))
   `(highlight ((,class (:foreground ,fg3 :background ,bg3))))
   `(hl-line ((,class (:background  ,bg2))))
   `(fringe ((,class (:background ,bg2 :foreground ,fg4))))
   `(cursor ((,class (:background ,bg3))))
   `(show-paren-match-face ((,class (:background ,warning))))
   `(isearch ((,class (:bold t :foreground ,warning :background ,bg3))))
   `(mode-line ((,class (:box (:line-width 1 :color nil) :bold t :foreground ,fg1 :background ,bg1))))
   `(mode-line-inactive ((,class (:box (:line-width 1 :color nil :style pressed-button) :foreground ,key3 :background ,bg1 :weight normal))))
   `(mode-line-highlight ((,class (:foreground ,keyword :box nil :weight bold))))
   `(mode-line-emphasis ((,class (:foreground ,fg2))))
   `(vertical-border ((,class (:foreground ,fg1))))
   `(minibuffer-prompt ((,class (:bold t :foreground ,keyword))))
   `(default-italic ((,class (:italic t))))
   `(link ((,class (:foreground ,const :underline t))))
   `(org-code ((,class (:foreground ,fg2))))
   `(org-hide ((,class (:foreground ,fg4))))
  ;`(org-level-1 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-2 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-3 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-4 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-5 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-6 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-7 ((,class (:bold t :foreground ,fg2 :height 1.1))))
  ;`(org-level-8 ((,class (:bold t :foreground ,fg2 :height 1.1))))
   `(org-level-1 ((,class (:bold t :foreground ,fg2))))
   `(org-level-2 ((,class (:bold t :foreground ,fg2))))
   `(org-level-3 ((,class (:bold t :foreground ,fg2))))
   `(org-level-4 ((,class (:bold t :foreground ,fg2))))
   `(org-level-5 ((,class (:bold t :foreground ,fg2))))
   `(org-level-6 ((,class (:bold t :foreground ,fg2))))
   `(org-level-7 ((,class (:bold t :foreground ,fg2))))
   `(org-level-8 ((,class (:bold t :foreground ,fg2))))
   `(org-italic ((,class (:italic t))))
   `(org-footnote  ((,class (:underline t :foreground ,fg4))))
   `(org-link ((,class (:underline t :foreground ,type ))))
   `(org-special-keyword ((,class (:foreground ,keyword))))
   `(org-verbatim ((,class (:foreground ,bg3 :underline t :slant italic))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-todo ((,class (:foreground ,keyword :bold t))))
   `(org-done ((,class (:foreground ,keyword :bold t))))
   `(org-warning ((,class (:foreground ,keyword :bold t))))
   `(org-ellipsis ((,class (:foreground ,builtin))))
   `(org-verbatim ((,class (:foreground ,fg4))))
   `(org-document-info-keyword ((,class (:foreground ,const))))
   `(org-date ((,class (:foreground ,type ))))
   `(font-latex-bold-face ((,class (:foreground ,const))))
   `(font-latex-italic-face ((,class (:foreground ,key3 :italic t))))
   `(font-latex-string-face ((,class (:foreground ,str))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,const))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,var))))
   `(ido-only-match ((,class (:foreground ,warning))))
   `(org-sexp-date ((,class (:foreground ,fg4))))
   `(ido-first-match ((,class (:foreground ,keyword :bold t))))
   `(gnus-header-content ((,class (:foreground ,keyword))))
   `(gnus-header-from ((,class (:foreground ,var))))
   `(gnus-header-name ((,class (:foreground ,type))))
   `(gnus-header-subject ((,class (:foreground ,func :bold t))))
   `(mu4e-view-url-number-face ((,class (:foreground ,type))))
   `(mu4e-cited-1-face ((,class (:foreground ,fg2))))
   `(mu4e-cited-7-face ((,class (:foreground ,fg3))))
   `(mu4e-header-marks-face ((,class (:foreground ,type))))
   `(ffap ((,class (:foreground ,fg4))))
   `(js2-private-function-call ((,class (:foreground ,const))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,str))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,key2))))
   `(js2-external-variable ((,class (:foreground ,const  ))))
   `(warning ((,class (:foreground ,warning))))
   `(ac-completion-face ((,class (:underline t :foreground ,type))))
   `(info-quoted-name ((,class (:foreground ,builtin))))
   `(info-string ((,class (:foreground ,str))))
   `(icompletep-determined ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-current-face ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-register-face ((,class :foreground ,keyword)))
   `(undo-tree-visualizer-default-face ((,class :foreground ,fg2)))
   `(undo-tree-visualizer-unmodified-face ((,class :foreground ,var)))
   `(undo-tree-visualizer-register-face ((,class :foreground ,type)))
   `(slime-repl-inputed-output-face ((,class (:foreground ,type))))
   `(magit-process-ok ((,class :foreground ,type)))
   `(trailing-whitespace ((,class :foreground nil :background ,warning)))
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,fg1)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,type)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,var)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,const)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,keyword)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,fg1)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,type)))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,var)))
   `(magit-item-highlight ((,class :background ,bg2)))
   `(magit-section-heading        ((,class (:foreground ,keyword :weight bold))))
   `(magit-hunk-heading           ((,class (:background ,bg3))))
   `(magit-section-highlight      ((,class (:background ,bg2))))
   `(magit-hunk-heading-highlight ((,class (:background ,bg3))))
   `(magit-diff-context-highlight ((,class (:background ,bg3 :foreground ,fg3))))
   `(magit-diffstat-added   ((,class (:foreground ,type))))
   `(magit-diffstat-removed ((,class (:foreground ,var))))
   `(magit-process-ok ((,class (:foreground ,func :weight bold))))
   `(magit-process-ng ((,class (:foreground ,warning :weight bold))))
   `(magit-branch ((,class (:foreground ,const :weight bold))))
   `(magit-log-author ((,class (:foreground ,fg3))))
   `(magit-hash ((,class (:foreground ,fg2))))
   `(web-mode-builtin-face ((,class (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face ((,class (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face ((,class (:inherit ,font-lock-constant-face))))
   `(web-mode-keyword-face ((,class (:foreground ,keyword))))
   `(web-mode-doctype-face ((,class (:inherit ,font-lock-comment-face))))
   `(web-mode-function-name-face ((,class (:inherit ,font-lock-function-name-face))))
   `(web-mode-string-face ((,class (:foreground ,str))))
   `(web-mode-type-face ((,class (:inherit ,font-lock-type-face))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,var))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,const))))
   `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
   `(web-mode-html-tag-face ((,class (:foreground ,fg3))))
   `(jde-java-font-lock-package-face ((t (:foreground ,var))))
   `(jde-java-font-lock-public-face ((t (:foreground ,keyword))))
   `(jde-java-font-lock-private-face ((t (:foreground ,keyword))))
   `(jde-java-font-lock-constant-face ((t (:foreground ,const))))
   `(jde-java-font-lock-modifier-face ((t (:foreground ,key3))))
   `(jde-java-font-lock-number-face ((t (:foreground ,var))))
   `(jde-java-font-lock-protected-face ((t (:foreground ,keyword))))
   `(company-echo ((,class (:foreground ,comment))))
   `(company-echo-common ((,class (:foreground ,comment))))
   `(company-tooltip ((,class (:background ,bg2 :foreground ,fg3))))
   `(company-tooltip-annotation ((,class (:background ,bg2 :foreground ,fg3))))
   `(company-tooltip-deprecated ((,class (:background ,bg2 :foreground ,fg3))))
   `(company-tooltip-common-selection ((,class (:foreground ,keyword :background ,bg3))))
   `(company-tooltip-selection ((,class (:foreground ,builtin :background ,bg3))))
   `(company-tooltip-search ((,class (:foreground ,bg2 :background ,bg3))))
   `(company-tooltip-serach-selection ((,class (:foreground ,builtin :background ,bg3))))
   `(diredfl-file-name ((,class (:foreground ,builtin))))
   `(diredfl-file-suffix ((,class (:foreground ,builtin))))
   `(diredfl-dir-name ((,class (:foreground ,builtin))))
   `(diredfl-flag-mark ((,class (:foreground ,builtin))))
   `(diredfl-flag-mark-line ((,class (:foreground ,builtin))))
   `(diredfl-date-time ((,class (:foreground ,comment))))
   `(diredfl-deletion ((,class (:foreground ,builtin))))
   `(diredfl-deletion-file-name ((,class (:foreground ,builtin))))
   `(diredfl-exec-priv ((,class (:foreground ,builtin))))
   `(diredfl-rare-priv ((,class (:foreground ,builtin))))
   `(diredfl-read-priv ((,class (:foreground ,builtin))))
   `(diredfl-link-priv ((,class (:foreground ,builtin))))
   `(diredfl-dir-priv ((,class (:foreground ,builtin))))
   `(diredfl-no-priv ((,class (:foreground ,builtin))))
   `(diredfl-write-priv ((,class (:foreground ,builtin))))
   `(diredfl-dir-heading ((,class (:foreground ,builtin))))
   `(diredfl-number ((,class (:foreground ,builtin))))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,warning)))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'micro-light)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; micro-light-theme.el ends here
